# Generated by Django 5.1.2 on 2024-10-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
        ('Genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='album name')),
                ('length', models.DurationField(verbose_name='album length')),
                ('cover', models.ImageField(upload_to='', verbose_name='album cover')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
                ('genre', models.ManyToManyField(max_length=100, to='Genre.genre', verbose_name='album genre')),
            ],
            options={
                'verbose_name': ('Album',),
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
