# Generated by Django 5.1.2 on 2024-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0002_alter_album_author'),
        ('Genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, to='Genre.genre', verbose_name='album genre'),
        ),
    ]
