# Generated by Django 5.1.2 on 2024-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='album_name')),
                ('length', models.TimeField(verbose_name='album_length')),
                ('genre', models.CharField(max_length=100, verbose_name='album_genre')),
                ('image', models.ImageField(upload_to='', verbose_name='album_genre')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='genre_name')),
                ('desription', models.TextField(verbose_name='genre_description')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='song_name')),
                ('length', models.TimeField(verbose_name='song_length')),
            ],
        ),
    ]
