# Generated by Django 5.1.2 on 2024-10-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='futhor name')),
            ],
            options={
                'verbose_name': ('Author',),
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='genre name')),
                ('description', models.TextField(verbose_name='genre description')),
            ],
            options={
                'verbose_name': ('Genre',),
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='album name')),
                ('length', models.DurationField(verbose_name='album length')),
                ('cover', models.ImageField(upload_to='', verbose_name='album cover')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.author')),
                ('genre', models.ManyToManyField(max_length=100, to='Music.genre', verbose_name='album genre')),
            ],
            options={
                'verbose_name': ('Album',),
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='song name')),
                ('length', models.DurationField(verbose_name='song length')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.author')),
                ('genre', models.ManyToManyField(to='Music.genre', verbose_name='song genre')),
            ],
            options={
                'verbose_name': ('Song',),
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
