# Generated by Django 5.1.2 on 2024-10-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='desription',
            new_name='description',
        ),
    ]
