# Generated by Django 5.1.2 on 2024-10-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_rename_desription_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='length',
            field=models.DurationField(verbose_name='album_length'),
        ),
    ]
