# Generated by Django 5.1.2 on 2024-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_alter_album_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(max_length=100, to='Music.genre', verbose_name='album_genre'),
        ),
    ]
