# Generated by Django 5.1.2 on 2024-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_remove_album_genre_album_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': ('Album',), 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': ('Genre',), 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': ('Song',), 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(max_length=100, to='Music.genre', verbose_name='album genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='album genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='length',
            field=models.DurationField(verbose_name='album length'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200, verbose_name='album name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(verbose_name='genre description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, verbose_name='genre name'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(verbose_name='song length'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200, verbose_name='song name'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(to='Music.genre', verbose_name='song genre'),
        ),
    ]
