# Generated by Django 5.1.2 on 2024-10-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_alter_album_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='album cover'),
        ),
    ]
