# Generated by Django 5.1.2 on 2024-10-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_album_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='cover',
        ),
    ]
