# Generated by Django 5.1.2 on 2024-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='futhor name')),
            ],
            options={
                'verbose_name': ('Author',),
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
