# Generated by Django 5.1.2 on 2024-10-27 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
        ('Author', '0001_initial'),
        ('Genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='song name')),
                ('length', models.DurationField(verbose_name='song length')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Album.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
                ('genre', models.ManyToManyField(to='Genre.genre', verbose_name='song genre')),
            ],
            options={
                'verbose_name': ('Song',),
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
