# Generated by Django 5.1.2 on 2024-10-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
        ('Author', '0001_initial'),
        ('Genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='song name')),
                ('file', models.FileField(upload_to='media/', verbose_name='song file')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Album.album', verbose_name='song album')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Author.author', verbose_name='song author')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Genre.genre', verbose_name='song genre')),
            ],
            options={
                'verbose_name': ('Song',),
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
