# Generated by Django 5.1.2 on 2024-11-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='songs/', verbose_name='song file'),
        ),
    ]
